### PR TITLE
Bugfix: Allow custom csv_options

### LINKED ISSUE #3: Custom csv_options are not set
The `set_csv_option` method only raises an exception if a passed option is unknown.  It should also update the `@csv_options` hash with new value.

https://github.com/drfeelngood/csv-machine/blob/4eca23c1a80764ad56a118aa86fab3e713d8fc51/lib/csv-machine.rb#L27-L29

### PR DESCRIPTION
**Pull request by GrumpyRainbow**
Run options:
# Running tests:

Finished tests in 0.003911s, 1022.7563 tests/s, 9716.1851 assertions/s.
4 tests, 38 assertions, 0 failures, 0 errors, 0 skips

ruby -v: ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-darwin13.0]

closes #3

### CODE REVIEW

File: lib/csv-machine.rb [hunk 1]
```diff
@@ -19,13 +19,14 @@ def csv_fields
     end
 
     def csv_options
-      @csv_options ||= CSV::DEFAULT_OPTIONS
+      @csv_options ||= CSV::DEFAULT_OPTIONS.dup
```
Comment (GrumpyRainbow) [inline lib/csv-machine.rb]: `CSV::DEFAULT_OPTIONS` is frozen, and is therefore uneditable

**Comment by drfeelngood** [comment]
:+1:

**Comment by drfeelngood** [comment]
```
Pushing gem to https://rubygems.org...
Successfully registered gem: csv-machine (1.0.1)
```
